config/routes.rb
Rails.application.routes.draw do

  get '/posts/unverified', to: 'posts#unverified'
  get '/posts/verified', to: 'posts#verified'
  post '/posts/:id/verify', to: 'posts#verify', as: :verify_post
  post '/posts/:id/ignore', to: 'posts#ignore', as: :ignore_post
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_action :verify_authenticity_token
  
  def new
  end

  def create
    @post = Post.new(url: params[:post][:url])
    @post.verified = false
    @post.ignored = false

    begin
      if @post.save
        redirect_to @post
      else
        redirect_to posts_path
      end
    rescue
      redirect_to posts_path
    end
  end

  def index
    @posts = Post.where verified: true
    @posts.shuffle
  end

  def unverified
    @posts = Post.where({ verified: false, ignored: false })
  end
  
  def verified
    @posts = Post.where({ verified: true, ignored: false })
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def verify
    @post = Post.find(params[:id])
    @post.verified = true
    @post.save
    redirect_to posts_unverified_path
  end

  def ignore
    @post = Post.find(params[:id])
    verified = @post.verified

    @post.ignored = true
    @post.verified = false
    @post.save

    if verified
      redirect_to posts_verified_path
    else
      redirect_to posts_unverified_path
    end      
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fbfilter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="margin-top: 0; margin-left: 0;">

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.2";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<% @posts.each do |p| %>
<div class="fb-post" data-href="<%= p.url %>" data-width="300"></div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
<p>
  <%= f.label :url %>
  <%= f.text_field :url %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1>Post</h1>

<ul>
  <li><%= @post.url %></li>
</ul>

app/views/posts/unverified.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.2";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<h1>List of unverified posts</h1>

<ul>
  <% @posts.each do |p| %>
    <li>
      <%= p.url %> <a class="post-preview-links" data-id="<%= p.id %>" href="#">view</a>
      <form action="<%= verify_post_path p.id %>" method="post"><input type="submit" value="Verify"></form>
    </li>
  <% end %>
</ul>

<div id="post_preview_id">
  <% @posts.each do |p| %>
    <div class="post-previews" style="display:none; padding: 10px; background: #707070;" id="post_preview_<%= p.id %>">
      <div class="fb-post" data-href="<%= p.url %>" data-width="500"></div>
    </div>
  <% end %>
</div>

<script>
 $(function(){
   $(".post-preview-links").click(function(){
     var pid = $(this).data('id');
     $(".post-previews").hide();
     $("#post_preview_" + pid).show();
     return false;
   });
 });
</script>

app/views/posts/verified.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.2";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div style="float: right;">
  [<a href="<%= posts_unverified_path %>">unverified</a>]
  [<a href="<%= posts_verified_path %>">verified</a>]
</div>

<h1>รายการโพสที่แสดงบนหน้าจอ</h1>
<hr>
<ul>
  <% @posts.each do |p| %>
    <li>
      <%= p.url %> <a class="post-preview-links" data-id="<%= p.id %>" href="#">view</a>
      <form style="display: inline-block;" action="<%= ignore_post_path p.id %>" method="post"><input type="submit" value="Ignore"></form>
    </li>
  <% end %>
</ul>

<div id="post_preview_id">
  <% @posts.each do |p| %>
    <div class="post-previews" style="display:none; padding: 10px; background: #707070;" id="post_preview_<%= p.id %>">
      <div class="fb-post" data-href="<%= p.url %>" data-width="500"></div>
    </div>
  <% end %>
</div>

<script>
 $(function(){
   $(".post-preview-links").click(function(){
     var pid = $(this).data('id');
     $(".post-previews").hide();
     $("#post_preview_" + pid).show();
     $("li").removeClass('selected');
     $(this).parents("li").addClass('selected');
     return false;
   });
 });
</script>

<style type="text/css">
  li.selected {
      background: #a0ffa0;
  }
</style>